name = "LeanDownstreamPlayground"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["LeanDownstreamPlayground"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "1ec8620912c93c3026dbd6720e3d9d3b6497eb23"

[[lean_lib]]
name = "LeanDownstreamPlayground"
