name: Bump mathlib dependency (opens PR)

on:
  schedule:
    - cron: "0 19 * * *"
  workflow_dispatch:

jobs:
  bump:
    uses: leanprover-community/downstream-reports/.github/workflows/bump-dependency-to-latest.yml@main
    with:
      skip-build: true
    permissions:
      contents: write
      pull-requests: write
      issues: write
      